# Generated by Django 4.2.3 on 2023-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=60)),
                ('edad', models.PositiveBigIntegerField(blank=True)),
                ('telefono', models.PositiveBigIntegerField(blank=True, max_length=10)),
                ('dni', models.CharField(blank=True, max_length=18, verbose_name='Codigo de DNI')),
                ('habitacion', models.PositiveBigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca del Vehiculo')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo del Vehiculo')),
                ('año', models.PositiveSmallIntegerField(blank=True, verbose_name='Año del Vehiculo')),
                ('placas', models.CharField(blank=True, max_length=10, verbose_name='Placas del Vehiculo')),
                ('conductor', models.CharField(blank=True, max_length=100, verbose_name='Nombre del conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residente', models.CharField(blank=True, max_length=60, verbose_name='Nombre del residente que visita')),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=60)),
                ('telefono', models.PositiveBigIntegerField(blank=True)),
                ('dni', models.CharField(blank=True, max_length=18, verbose_name='Codigo de DNI')),
            ],
        ),
    ]
